# Generated by Django 3.0.6 on 2020-05-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microcontroller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Нет описания', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Микроконтроллеры',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Нет описания', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Нет описания', verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='Сonnection_hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('topic', models.CharField(help_text='Топик должен быть уникален. Используйте формат: room№/microcontroller#/sensor№/', max_length=100, unique=True, verbose_name='Топик иерархии')),
                ('microcontroller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Microcontroller')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Room')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Sensor')),
            ],
            options={
                'verbose_name_plural': 'Иерархия подключения',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Значение')),
                ('connection_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Сonnection_hierarchy')),
            ],
            options={
                'verbose_name_plural': 'Температура',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Значение')),
                ('connection_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Сonnection_hierarchy')),
            ],
            options={
                'verbose_name_plural': 'Давление',
            },
        ),
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Значение')),
                ('connection_hierarchy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='climate_controls.Сonnection_hierarchy')),
            ],
            options={
                'verbose_name_plural': 'Влажность',
            },
        ),
    ]
