# Generated by Django 3.0.6 on 2020-05-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate_controls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сonnection_hierarchy',
            new_name='Connection_hierarchy',
        ),
    ]
